version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - database
    environment:
      - DB_URI=database
    container_name: backend

  database:
    image: mongo
    ports:
      - "27017:27017"
    container_name: fetchdb
